# SPDX-License-Identifier: LGPL-2.1-or-later

[Match]
Distribution=arch

[Content]
Splash=/usr/share/systemd/bootctl/splash-arch.bmp
Packages=
        mesa
        noto-fonts
        vulkan-intel
        zsh
        zsh-completions
	qemu-base