# SPDX-License-Identifier: LGPL-2.1-or-later

[Config]
MinimumVersion=26~devel

[Build]
ToolsTree=default
ToolsTreeSandboxTrees=mkosi.sandbox
SandboxTrees=mkosi.sandbox
History=yes
CacheDirectory=mkosi.cache
Incremental=yes

[Output]
OutputDirectory=mkosi.output
SplitArtifacts=uki,partitions
Format=disk
ImageId=ParticleOS
ManifestFormat=json
Output=%i_%v_%a

[Content]
SkeletonTrees=mkosi.skeleton
UnifiedKernelImageFormat=%i_%v_%a
KernelCommandLine=
        rw
        audit=0
        systemd.image_policy=esp=unprotected:xbootldr=unprotected+unused+absent:root=encrypted:swap=encrypted+unused+absent:home=unprotected:=ignore
InitrdProfiles=
KernelModulesInitrdExclude=.*
KernelModulesInitrdInclude=default
Hostname=particle-????-????

Packages=
        acl
        attr
        bash-completion
        btrfs-progs
        cpio
        curl
        dbus-broker
        diffutils
        dmidecode
        dosfstools
        erofs-utils
        fish
        fwupd
        gdb
        jq
        kbd
        less
        man
        mtools
        nano
        nftables
        nvme-cli
        opensc
        openssl
        p11-kit
        pkcs11-provider
        socat
        strace
        systemd
        tree
        udev
        unzip
        usbutils
        which
        wireguard-tools
        xxd
        zstd

[Validation]
SecureBoot=yes
SignExpectedPcr=yes
SecureBootSignTool=systemd-sbsign

[Runtime]
RuntimeSize=30G
RAM=4G
CPUs=4
Ephemeral=yes
RuntimeScratch=no
Credentials=
        passwd.plaintext-password.root=particleos
        tty.serial.hvc0.agetty.autologin=particleos
        tty.serial.hvc0.login.noauth=yes
        tty.console.agetty.autologin=particleos
        tty.console.login.noauth=yes
        tty.virtual.tty1.agetty.autologin=particleos
        tty.virtual.tty1.login.noauth=yes
