# SPDX-License-Identifier: LGPL-2.1-or-later

[Content]
Packages=
        cockpit
        cockpit-files
        cockpit-machines
        cockpit-podman
        e2fsprogs
        edk2-ovmf
        firewalld
        fuse-overlayfs
        libvirt
        podman
        podman-compose
        podman-docker
        tuned
        swtpm
        virt-install
        virt-viewer