# SPDX-License-Identifier: LGPL-2.1-or-later

[Content]
Packages=
        cockpit
        cockpit-files
        cockpit-machines
        cockpit-podman
        firewalld
        libvirt
        linux-firmware
        podman
        podman-compose
        virt-install