# SPDX-License-Identifier: LGPL-2.1-or-later

[Match]
Distribution=arch

[Content]
Packages=
        arch-install-scripts
        archlinux-keyring
        bash
        bzip2
        base-devel
        bat
        bpf
        ccid
        compsize
        cryptsetup
        dbus-broker-units
        expac
        file
        filesystem
        gawk
        gcc-libs
        glibc
        gettext
        git
        gnupg
        iproute2
        iputils
        libarchive
        libfido2
        libp11-kit
        libpwquality
        licenses
        linux
        linux-firmware
        man-db
        mkosi
        openssh
        quota-tools
        pacman
        pcsclite
        perf
        polkit
        procps-ng
        psmisc
        python3
        python-pefile
        python-pipx
        qrencode
        shadow
        scx-scheds
        sudo
        systemd-sysvcompat
        systemd-resolvconf
        systemd-ukify
        tgt
        tpm2-pkcs11
        tpm2-tools
        tpm2-tss
        vim-minimal
        xz
