# SPDX-License-Identifier: LGPL-2.1-or-later

[Match]
Distribution=arch

[Content]
Packages=
        arch-install-scripts
        base
        base-devel
        bat
        bpf
        ccid
        compsize
        cryptsetup
        dbus-broker-units
        expac
        git
        gnupg
        libarchive
        libfido2
        libp11-kit
        libpwquality
        linux
        linux-firmware
        man-db
        mkosi
        openssh
        quota-tools
        pcsclite
        perf
        polkit
        python3
        python-pefile
        python-pipx
        qrencode
        scx-scheds
        sudo
        systemd-resolvconf
        systemd-ukify
        tgt
        tpm2-pkcs11
        tpm2-tools
        tpm2-tss
        vim-minimal
