# SPDX-License-Identifier: LGPL-2.1-or-later

[Match]
Distribution=arch

[Content]
Packages=
        archlinux-keyring
        base-devel
        bash
        bpf
        bzip2
        ccid
        compsize
        cryptsetup
        dbus-broker-units
        expac
        gawk
        gettext
        gcc-libs
        git
        file
        filesystem
        iproute2
        iputils
        libfido2
        licenses
        linux
        man-db
        openssh
        pacman
        pcsclite
        perf
        polkit
        procps-ng
        psmisc
        python3
        qrencode
        shadow
        systemd-sysvcompat
        systemd-ukify
        tgt
        tpm2-tools
        tpm2-tss
        vim-minimal
