# SPDX-License-Identifier: LGPL-2.1-or-later

[Match]
Distribution=fedora

[Content]
Splash=/usr/share/pixmaps/fedora-logo.png
Packages=
        fedora-logos
        kernel-modules
        mesa-dri-drivers
        mesa-vulkan-drivers
        qemu-kvm
